### PR TITLE
Example for sending requests via a serverless function

### PR DESCRIPTION
**Pull request by kaytwo**
This is a minimum working example for cloudflare pages + functions to use a serverless function to call the amadeus api. Important things to note:

When you develop locally, you'll need to add the relevant API keys to the command line in `package.json` where I have my example API_KEY in there. You'll need to add the secret as well. That shouldn't be in a file that is in version control, but it is what it is. You can use `npm run fullstack-start` to simulate the server side functions, and `npm start` for a normal client-side only react app development experience.

When you deploy to production, you need to put your environment variables in the website:

image

Then in production, the code in the functions directory will get deployed and run on the server side rather than the client side, and you can interact with it via `fetch` from the client side:

image

This should help you get up to speed and get stuff going. Please reach out if you've got any other questions.

### CODE REVIEW

**Comment by mohassan914** [comment]
Hello professor, we have looked over your PR and we are grateful you were
able to help our group. From my understanding, it would make more sense if
we approved of this PR because some of the code was cleaned up. Should we
approve the changes you made in the PR?  Also, do we need to host it on
cloudflare pages ourselves or can we use what you have provided us. In
other words, what would be the next valuable steps that our group can
take?
Best regards, Mohamed Hassan

**Comment by kaytwo** [comment]
I would recommend merging it and hosting it in your own cloud flare pages
account

**Comment by mohassan914** [comment]
Hello professor, it seems that one of the topics which was covered in class
came back to haunt me.
[image: Screen Shot 2022-11-30 at 9.32.15 PM.png]
I was following a tutorial on how to obtain access tokens via axios the
easy way and I get hit with the following error. If I understand correctly,
It has something to do with server side issues again. I am trying to obtain
a token via an auth function that I am trying to write in one of the
functions.js files so then I can gain access to the data. Long story short,
it is preventing me from authenticating and is causing issues. From the top
of your head, would there be any short term fixes?
[image: Screen Shot 2022-11-30 at 9.39.43 PM.png]
This is the following helloworld.js function modfired to return this
response. If I understand correctly, all I will need to do is just wait for
it to fetch on the app.js file and it should update it via the token.
[image: Screen Shot 2022-11-30 at 9.41.48 PM.png]
This is the request greeting that I am still using. Only in this instance,
as opposed to just writing the client key, I am trying to return the Json
containing the token and everything from the CURL command we ran earlier.
I tried modifying it and achieved little success. Are there any
recommendations you can give us? We have been stuck on this for a while
now.
-Mohamed Hassan

**Comment by kaytwo** [comment]
Your screenshots didn't come through in gh

**Pull request merged**
